name: reminder

on:
  schedule:
    - cron: "*/5 * * * *"

jobs:
  reminder:
    runs-on: ubuntu-latest

    steps:
      - name: set up git repository
        uses: actions/checkout@v2

      - name: remind developers
        run: echo "Remember to stay on updating something new for this repository!"
        
      - name: Send Email Notification
        env:
          SMTP_SERVER: ${{ secrets.SMTP_SERVER }}
          SMTP_PORT: ${{ secrets.SMTP_PORT }}
          SMTP_USERNAME: ${{ secrets.SMTP_USERNAME }}
          SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
          EMAIL_FROM: ${{ secrets.EMAIL_FROM }}
          EMAIL_TO: ${{ secrets.EMAIL_TO }}
        run: |
          echo "Subject: Reminder - Update Something New" | \
          /usr/sbin/sendmail -S $SMTP_SERVER:$SMTP_PORT \
                            -au $SMTP_USERNAME \
                            -ap $SMTP_PASSWORD \
                            -f $EMAIL_FROM \
                            $EMAIL_TO
